### YamlMime:QSharpNamespace
uid: microsoft.quantum.environment
name: Microsoft.Quantum.Environment
summary: " # <a name=\"summary\"></a>摘要\n 這些函式會提供發生量子計算之環境的相關資訊。"
operations:
- uid: microsoft.quantum.environment.getqubitsavailabletoborrow
  summary: >-
    傳回目前可供借用的量子位數目。

    這包括未使用的量子位;也就是說，這包括所傳回的量子位 `GetQubitsAvailableToUse` 。
- uid: microsoft.quantum.environment.getqubitsavailabletouse
  summary: 傳回目前可供使用的量子位數目。
metadata:
  ms.openlocfilehash: 7f597d8f429089b0ebf2c22cef1d1b98ea270402
  ms.sourcegitcommit: d6ac6f4345be0dd68f1bcd944f44b08e7a3cf346
  ms.translationtype: MT
  ms.contentlocale: zh-TW
  ms.lasthandoff: 09/02/2020
  ms.locfileid: "89341151"
