### YamlMime:QSharpType
uid: microsoft.quantum.environment.getqubitsavailabletouse
name: GetQubitsAvailableToUse
type: operation
namespace: Microsoft.Quantum.Environment
summary: 傳回目前可供使用的 qubits 數目。
syntax: 'operation GetQubitsAvailableToUse () : Int'
input:
  content: ()
  types: []
output:
  content: Int
  types:
  - summary: >-
      可以在 `using` 語句中配置的 qubits 數目。

      如果使用的目的電腦未提供此資訊，則會傳回 `-1`。
    isPrimitive: true
    uid: Int
seeAlso:
- getqubitsavailabletoborrow
ms.openlocfilehash: 1cb1331aa26ec9755a9e379336f46387b61bb0ae
ms.sourcegitcommit: 8becfb03eb60ba205c670a634ff4daa8071bcd06
ms.translationtype: MT
ms.contentlocale: zh-TW
ms.lasthandoff: 10/31/2019
ms.locfileid: "73230461"
