### YamlMime:QSharpNamespace
functions: []
name: Microsoft.Quantum.Environment
newtypes: []
operations:
- summary: 傳回目前可供借用的量子位數目。
  uid: Microsoft.Quantum.Environment.GetQubitsAvailableToBorrow
- summary: 傳回目前可供使用的量子位數目。
  uid: Microsoft.Quantum.Environment.GetQubitsAvailableToUse
summary: 這些函式會提供發生量子計算之環境的相關資訊。
uid: Microsoft.Quantum.Environment
metadata:
  ms.openlocfilehash: 87e1659f8ecdd6df99271f7552f683ffed85b151
  ms.sourcegitcommit: a87c1aa8e7453360025e47ba614f25b02ea84ec3
  ms.translationtype: MT
  ms.contentlocale: zh-TW
  ms.lasthandoff: 11/26/2020
  ms.locfileid: "96201439"
