### YamlMime:QSharpType
uid: microsoft.quantum.environment.getqubitsavailabletouse
name: GetQubitsAvailableToUse
type: operation
namespace: Microsoft.Quantum.Environment
summary: 傳回目前可供使用的 qubits 數目。
syntax: 'operation GetQubitsAvailableToUse () : Int'
input:
  content: ()
  types: []
output:
  content: Int
  types:
  - summary: >-
      可以在 `using` 語句中配置的 qubits 數目。

      如果使用的目的電腦未提供此資訊，則會傳回 `-1`。
    isPrimitive: true
    uid: Int
seeAlso:
- getqubitsavailabletoborrow
metadata:
  ms.openlocfilehash: 1cb1331aa26ec9755a9e379336f46387b61bb0ae
  ms.sourcegitcommit: edcf15044d7bdf4f8b21fb8f6af4bde475eb13a0
  ms.translationtype: MT
  ms.contentlocale: zh-TW
  ms.lasthandoff: 11/05/2019
  ms.locfileid: "73230461"
