### YamlMime:QSharpType
uid: microsoft.quantum.chemistry.jordanwigner.preparesparsemulticonfigurationalstate
name: PrepareSparseMultiConfigurationalState
type: operation
namespace: microsoft.quantum.chemistry.jordanwigner
summary: 藉由將 excitations 新增到初始試用狀態，來準備試用狀態的稀疏多重 configurational 狀態。
syntax: 'operation PrepareSparseMultiConfigurationalState (initialStatePreparation : (Qubit[] => Unit), excitations : Microsoft.Quantum.Chemistry.JordanWigner.JordanWignerInputState[], qubits : Qubit[]) : Unit'
input:
  content: '(initialStatePreparation : (Qubit[] => Unit), excitations : Microsoft.Quantum.Chemistry.JordanWigner.JordanWignerInputState[], qubits : Qubit[])'
  types:
  - name: initialStatePreparation
    summary: 單一準備初始試用狀態。
    isOperation: true
    input:
      types:
      - isArray: true
        isPrimitive: true
        uid: Qubit
    output:
      types:
      - isPrimitive: true
        uid: Unit
  - name: excitations
    summary: 初始試用狀態的 Excitations，由 excitation 的波幅和 excitation 作用所在的量子位索引所代表。
    isArray: true
    uid: microsoft.quantum.chemistry.jordanwigner.jordanwignerinputstate
  - name: qubits
    summary: Hamiltonian 的量子位。
    isArray: true
    isPrimitive: true
    uid: Qubit
output:
  content: Unit
  types:
  - isPrimitive: true
    uid: Unit
metadata:
  ms.openlocfilehash: cb4a90a4686c26139f956ae7438fd1da6b38897b
  ms.sourcegitcommit: d6ac6f4345be0dd68f1bcd944f44b08e7a3cf346
  ms.translationtype: MT
  ms.contentlocale: zh-TW
  ms.lasthandoff: 09/02/2020
  ms.locfileid: "89339298"
