### YamlMime:QSharpNamespace
uid: microsoft.quantum.environment
name: Microsoft 量子環境
summary: " # <a name=\"summary\"></a>總結\n 這些函式會提供發生配量計算之環境的相關資訊。"
operations:
- uid: microsoft.quantum.environment.getqubitsavailabletoborrow
  summary: >-
    傳回目前可供借用的 qubits 數目。

    這包括未使用的 qubits;也就是說，這包括 `GetQubitsAvailableToUse`傳回的 qubits。
- uid: microsoft.quantum.environment.getqubitsavailabletouse
  summary: 傳回目前可供使用的 qubits 數目。
ms.openlocfilehash: 50e5cfb7c1b9a4075c25b2705d00b435a09e159e
ms.sourcegitcommit: 8becfb03eb60ba205c670a634ff4daa8071bcd06
ms.translationtype: MT
ms.contentlocale: zh-TW
ms.lasthandoff: 10/30/2019
ms.locfileid: "73056822"
