### YamlMime:QSharpType
uid: microsoft.quantum.environment.getqubitsavailabletouse
name: GetQubitsAvailableToUse
type: operation
namespace: microsoft.quantum.environment
summary: 傳回目前可供使用的量子位數目。
syntax: 'operation GetQubitsAvailableToUse () : Int'
input:
  content: ()
  types: []
output:
  content: Int
  types:
  - summary: >-
      可以在語句中配置的量子位數目 `using` 。

      如果正在使用的目的電腦未提供此資訊，則 `-1` 會傳回。
    isPrimitive: true
    uid: Int
seeAlso:
- getqubitsavailabletoborrow
metadata:
  ms.openlocfilehash: 326195ba3fa7b880d9b6871d16ea7a12c1c9a2ea
  ms.sourcegitcommit: 685a8ab16d7e6a25e63a168d6e7c385fa6e876cc
  ms.translationtype: MT
  ms.contentlocale: zh-TW
  ms.lasthandoff: 09/29/2020
  ms.locfileid: "91484728"
