### YamlMime:QSharpType
uid: microsoft.quantum.environment.getqubitsavailabletoborrow
name: GetQubitsAvailableToBorrow
type: operation
namespace: microsoft.quantum.environment
summary: >-
  傳回目前可供借用的量子位數目。

  這包括未使用的量子位;也就是說，這包括所傳回的量子位 `GetQubitsAvailableToUse` 。
syntax: 'operation GetQubitsAvailableToBorrow () : Int'
input:
  content: ()
  types: []
output:
  content: Int
  types:
  - summary: >-
      可以在語句中配置的量子位數目 `borrowing` 。

      如果正在使用的目的電腦未提供此資訊，則 `-1` 會傳回。
    isPrimitive: true
    uid: Int
seeAlso:
- getqubitsavailabletouse
metadata:
  ms.openlocfilehash: 18e68548e9f344a70dac95f70528a8b3e87f5909
  ms.sourcegitcommit: 685a8ab16d7e6a25e63a168d6e7c385fa6e876cc
  ms.translationtype: MT
  ms.contentlocale: zh-TW
  ms.lasthandoff: 09/29/2020
  ms.locfileid: "91478064"
