### YamlMime:QSharpType
uid: microsoft.quantum.chemistry.jordanwigner.preparesingleconfigurationalstatesinglesiteoccupation
name: PrepareSingleConfigurationalStateSingleSiteOccupation
type: operation
namespace: Microsoft.Quantum.Chemistry.JordanWigner
summary: 藉由佔用微調 orbitals 來準備試用狀態的簡單狀態
syntax: 'operation PrepareSingleConfigurationalStateSingleSiteOccupation (qubitIndices : Int[], qubits : Qubit[]) : Unit'
input:
  content: '(qubitIndices : Int[], qubits : Qubit[])'
  types:
  - name: qubitIndices
    summary: Electrons 所要佔用的 qubits 索引。
    isArray: true
    isPrimitive: true
    uid: Int
  - name: qubits
    summary: Hamiltonian 的 Qubits。
    isArray: true
    isPrimitive: true
    uid: Qubit
output:
  content: Unit
  types:
  - isPrimitive: true
    uid: Unit
functors:
- Adjoint
- Controlled
ms.openlocfilehash: a7ed22f7f458a515cf1c19c54a841f8c16e317fe
ms.sourcegitcommit: 8becfb03eb60ba205c670a634ff4daa8071bcd06
ms.translationtype: MT
ms.contentlocale: zh-TW
ms.lasthandoff: 10/31/2019
ms.locfileid: "73231821"
